apiVersion: apps/v1
kind: Deployment
metadata:
  name: intro-to-do-app
  labels:
    app: intro-to-do-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intro-to-do-app
  template:
    metadata:
      labels:
        app: intro-to-do-app
    spec:
      containers:
      - name: intro-to-do-app
        image: guptapranav/intro-to-do-app
        ports:
        - containerPort: 3000
